{% set name = "types-awscrt" %}
{% set version = "0.29.0" %}
{% set lib_version = version.split(".post")[0] %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f81040846095cbaf64e6b79040434750d4f2f487544d7748b778c349d393510

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - pip

test:
  requires:
    - pip
    - poetry
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import importlib; importlib.import_module('awscrt-stubs')"

about:
  home: https://github.com/youtype/types-awscrt
  summary: Type annotations for AWS awscrt {{ lib_version }} library
  dev_url: https://github.com/youtype/types-awscrt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vemel
