{% set name = "types-awscrt" %}
{% set version = "0.16.12" %}
{% set lib_version = version.split(".post")[0] %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fca34b9c30e39567838adc51cc186fae92d702741c7aaf835e19c3eb1bd4d8dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.7,<4.0
    - pip

test:
  requires:
    - pip
    - poetry
  commands:
    - pip check
    - python -c "import importlib; importlib.import_module('awscrt-stubs')"

about:
  home: https://github.com/youtype/types-awscrt
  summary: Type annotations for AWS awscrt {{ lib_version }} library
  dev_url: https://github.com/youtype/types-awscrt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vemel
